---
  database:
      dialect: "sqlite"
      storage: '/tmp/test_breakout_db.sqlite'
  redis:
    ranking:
      host: "127.0.0.1"
      port: 6379
      db: 5
    session:
      host: "127.0.0.1"
      port: 6379
      db: 6
  log4js:
    appenders:
      stdout: # 標準出力
        type: 'console'
      stderr: # 標準エラー出力
        type: 'stderr'
    categories:
      default:
        appenders:
          - 'stdout'
        level: 'info'
      access:
        appenders:
          - 'stdout'
        level: 'info'
      batch:
        appenders:
          - "stdout"
        level: "info"
      error:
        appenders:
          - 'stderr'
        level: 'info'